# Generated by Django 4.0.3 on 2022-03-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
